In [22]:
import numpy as np

In [23]:
np.set_printoptions(precision=2)

In [24]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int64


In [25]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [26]:
c = np.array([
    [[1,2,3],
    [2,3,4],
    [2,2,2]],
    [[1,2,3],
    [2,3,4],
    [2,2,2]],
    ])

print(c)
print(c.shape)
print(c.dtype)

[[[1 2 3]
  [2 3 4]
  [2 2 2]]

 [[1 2 3]
  [2 3 4]
  [2 2 2]]]
(2, 3, 3)
int64


In [27]:
import numpy as np

c = np.array([
    [
        [[1, 2, 3],
         [2, 3, 4],
         [2, 2, 2]],

        [[1, 2, 3],
         [2, 3, 4],
         [2, 2, 2]]
    ],
    [
        [[4, 5, 6],
         [5, 6, 7],
         [6, 6, 6]],

        [[4, 5, 6],
         [5, 6, 7],
         [6, 6, 6]]
    ],
    [
        [[7, 8, 9],
         [8, 9, 10],
         [9, 9, 9]],

        [[7, 8, 9],
         [8, 9, 10],
         [9, 9, 9]]
    ]
])

print("4D Array:")
print(c.dtype)
print(c.shape)

4D Array:
int64
(3, 2, 3, 3)


In [28]:
import numpy as np

c = np.array([
    [
        [
            [[1, 2, 3],
             [2, 3, 4],
             [2, 2, 2]],

            [[1, 2, 3],
             [2, 3, 4],
             [2, 2, 2]]
        ],
        [
            [[4, 5, 6],
             [5, 6, 7],
             [6, 6, 6]],

            [[4, 5, 6],
             [5, 6, 7],
             [6, 6, 6]]
        ]
    ],
    [
        [
            [[7, 8, 9],
             [8, 9, 10],
             [9, 9, 9]],

            [[7, 8, 9],
             [8, 9, 10],
             [9, 9, 9]]
        ],
        [
            [[10, 11, 12],
             [11, 12, 13],
             [12, 12, 12]],

            [[10, 11, 12],
             [11, 12, 13],
             [12, 12, 12]]
        ]
    ]
])

print("5D Array:")
print(c.shape)

5D Array:
(2, 2, 2, 3, 3)


generate matrix
- linear
- random

In [29]:
a = np.arange(1,100,5)
print(a)
a.size

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


20

In [30]:
a = np.arange(1,10,.2)
print(a)
a.size

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


45

In [33]:
#you decide the gap
a = np.arange(-np.pi,np.pi,.25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [35]:
#if you want to get the number of items and gaps is decided by np use linspace
#you decide number of elements
b = np.linspace(1,100,100)
print(b)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


In [40]:
#respahe changes the number of 
b.reshape(5,5,2,2)

array([[[[  1.,   2.],
         [  3.,   4.]],

        [[  5.,   6.],
         [  7.,   8.]],

        [[  9.,  10.],
         [ 11.,  12.]],

        [[ 13.,  14.],
         [ 15.,  16.]],

        [[ 17.,  18.],
         [ 19.,  20.]]],


       [[[ 21.,  22.],
         [ 23.,  24.]],

        [[ 25.,  26.],
         [ 27.,  28.]],

        [[ 29.,  30.],
         [ 31.,  32.]],

        [[ 33.,  34.],
         [ 35.,  36.]],

        [[ 37.,  38.],
         [ 39.,  40.]]],


       [[[ 41.,  42.],
         [ 43.,  44.]],

        [[ 45.,  46.],
         [ 47.,  48.]],

        [[ 49.,  50.],
         [ 51.,  52.]],

        [[ 53.,  54.],
         [ 55.,  56.]],

        [[ 57.,  58.],
         [ 59.,  60.]]],


       [[[ 61.,  62.],
         [ 63.,  64.]],

        [[ 65.,  66.],
         [ 67.,  68.]],

        [[ 69.,  70.],
         [ 71.,  72.]],

        [[ 73.,  74.],
         [ 75.,  76.]],

        [[ 77.,  78.],
         [ 79.,  80.]]],


       [[[ 81.,  82.],
         

In [41]:
print(np.random.rand(3,3))

[[0.53 0.01 0.78]
 [0.49 0.93 0.  ]
 [0.98 0.44 0.67]]


In [42]:
print(np.random.randn(2,2))

[[-0.17  0.01]
 [ 1.34 -0.3 ]]


In [44]:
print(np.random.randint(1,100, (10,10)))

[[44 38 96 67 12 81 83 10  2 93]
 [27 72 57 24 27 53 25 50 96 10]
 [36 82 49  3 32 82 25 71 14 55]
 [83 40 27  2 72 66 92 33  3 60]
 [68 49 79 93 31 16 37 66 48 83]
 [70 13 16 73 75 61 21 98 97 50]
 [17  6  7 74 18 83 35 26 72 10]
 [93 56 65 48 68 66  1 97 13 69]
 [79 71 37 18 56 47 18 20 39 69]
 [48 23 82 87 73  7 58 84  1 96]]


In [47]:
x = np.random.randint(1,11, (3,3))
y = np.random.randint(1,11,(3,3))
print(x + y)
print(x * y)
print(x-10)

[[ 7 13  9]
 [ 9  2  5]
 [ 6  2 14]]
[[12 40 14]
 [14  1  4]
 [ 9  1 48]]
[[-7 -2 -8]
 [-8 -9 -9]
 [-7 -9 -2]]


In [48]:
x.dot(y)

array([[74, 25, 65],
       [18, 12, 24],
       [43, 24, 73]])