Write a NumPy program to create an array of 10 zeros.
Write a NumPy program to create an array of 10 ones.

In [2]:
import numpy as np

In [5]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

In [8]:
x = np.random.randint(0,8, (3,3))
print(x)

[[5 1 2]
 [3 2 5]
 [0 1 5]]


Write a NumPy program to reverse an array (first element becomes the last).

In [16]:
arr = np.random.randint(0,5,(10))
arr2 = np.arange(0,10)
print(arr)
print(arr[::-1])
print("-"*10)
print(arr2)
print(arr2[::-1])

[1 4 4 1 1 2 1 1 2 4]
[4 2 1 1 2 1 1 4 4 1]
----------
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Write a NumPy program to extract all odd numbers from an array.

In [18]:
arr = np.arange(0,10)
for i in arr:
    if i%2 == 0:
        print(i)

0
2
4
6
8


Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

In [22]:
x = np.arange(6)
print(x)
print("mean", np.mean(x))
print("sum",np.sum(x))
print("standard deviation", np.std(x))

[0 1 2 3 4 5]
mean 2.5
sum 15
standard deviation 1.707825127659933


Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

In [27]:
arr = np.random.randint(0,100,(5,5))
print(arr)
print("min", np.min(arr))
print("max", np.max(arr))

[[14 42 28 76 89]
 [21 49 10  2 17]
 [70 67 73 47 95]
 [71 97 27 22 49]
 [12 68 44 49 54]]
min 2
max 97


Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [31]:
arr = np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Write a NumPy program to multiply two given matrices.

In [39]:
arr1 = np.random.randint(1,10,(5,5))
arr2 = np.random.randint(1,10,(5,5))
print(arr1.dot(arr2))

[[108 146 178  29  91]
 [116 126 162  57 111]
 [136 144 222  46 128]
 [ 44  40  72  21  45]
 [169 205 260  76 171]]


Write a NumPy program to find the unique elements of an array.

In [41]:
print(np.unique(arr1))

[1 2 3 4 5 6 7 8 9]


Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.
Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.
Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

In [53]:
arr1 = np.random.randint(1,10,(5,5))
print(arr1)
arr2 = arr1[:,0::2] #odd column
arr3 = arr1[0::2, :] #odd rows
arr4 = arr1[0:3, 1:4] # 3 rows, 1-4 column number
print(arr2,"\n", arr3, "\n", arr4)

[[2 3 1 9 6]
 [9 2 8 7 4]
 [9 1 5 9 1]
 [8 8 7 7 7]
 [2 1 4 4 3]]
[[2 1 6]
 [9 8 4]
 [9 5 1]
 [8 7 7]
 [2 4 3]] 
 [[2 3 1 9 6]
 [9 1 5 9 1]
 [2 1 4 4 3]] 
 [[3 1 9]
 [2 8 7]
 [1 5 9]]


Write a NumPy program to reverse the order of elements in each column of a 2D array.

In [55]:
arr1 = np.random.randint(1,10,(5,5))
print(arr1)
arr2 = arr1[:,::-1]
print(arr2)

[[9 5 4 7 2]
 [6 7 3 8 2]
 [1 7 3 4 6]
 [2 8 6 4 1]
 [6 3 8 6 8]]
[[2 7 4 5 9]
 [2 8 3 7 6]
 [6 4 3 7 1]
 [1 4 6 8 2]
 [8 6 8 3 6]]


Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

In [73]:
arr1 = np.random.randint(1,10,(10))
print(arr1)
arr1_len = len(arr1)
diag = np.zeros((arr1_len, arr1_len))
# print(diag)
for i in range(arr1_len):
    for j in range(arr1_len):
        if i == j:
            diag[i,j] = arr1[i]
        # if i+1 == j:
        #     diag[i, j] = arr1[j] ** 2
        if i < j:
            diag[i, j] = arr1[j] ** 2
print(diag)

[3 1 8 8 8 4 9 1 3 6]
[[ 3.  1. 64. 64. 64. 16. 81.  1.  9. 36.]
 [ 0.  1. 64. 64. 64. 16. 81.  1.  9. 36.]
 [ 0.  0.  8. 64. 64. 16. 81.  1.  9. 36.]
 [ 0.  0.  0.  8. 64. 16. 81.  1.  9. 36.]
 [ 0.  0.  0.  0.  8. 16. 81.  1.  9. 36.]
 [ 0.  0.  0.  0.  0.  4. 81.  1.  9. 36.]
 [ 0.  0.  0.  0.  0.  0.  9.  1.  9. 36.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  9. 36.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  3. 36.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  6.]]
